spring:
  application:
    name: snappin

  jackson:
    time-zone: Asia/Seoul
    property-naming-strategy: SNAKE_CASE

  batch:
    jdbc:
      initialize-schema: never

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
