spring:
  application:
    name: snappin

  batch:
    jdbc:
      initialize-schema: never

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
