spring:
  application:
    name: snappin

  jackson:
    time-zone: Asia/Seoul

  batch:
    jdbc:
      initialize-schema: never

  security:
    user:
      name: disabled
      password: disabled

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
